"use client";
import {useEffect,useMemo,useState} from "react";
import {Building2,TriangleAlert,Sparkles,Plus,UploadCloud,RotateCcw,CheckCircle2} from "lucide-react";

type Project={id:string;name:string;city:string;type:string;valueCr:number;progress:number;planned:number;budgetPlan:number;budgetActual:number};
const starter:Project[]=[
{id:"horizon",name:"Horizon Heights",city:"Gurugram",type:"Residential",valueCr:120,progress:37,planned:44,budgetPlan:500,budgetActual:541},
{id:"greenview",name:"Greenview Towers",city:"Noida",type:"Residential",valueCr:88,progress:61,planned:61,budgetPlan:420,budgetActual:409},
{id:"metro",name:"Metro Square",city:"Delhi",type:"Commercial",valueCr:54,progress:29,planned:35,budgetPlan:310,budgetActual:318},
{id:"lakeview",name:"Lakeview Villas",city:"Faridabad",type:"Villas",valueCr:24,progress:82,planned:80,budgetPlan:160,budgetActual:151}
];
function health(p:Project){const gap=p.planned-p.progress,b=p.budgetActual-p.budgetPlan;if(gap>=8||(p.budgetPlan>0&&b/p.budgetPlan>=.08))return{label:"Critical",tone:"red"};if(gap>=3||b>0)return{label:"Watch",tone:"amber"};return{label:"Healthy",tone:"green"}}
export default function Home(){
const[projects,setProjects]=useState<Project[]>([]),[loaded,setLoaded]=useState(false),[selected,setSelected]=useState<Project|null>(null),[showNew,setShowNew]=useState(false),[showUpload,setShowUpload]=useState(false),[q,setQ]=useState(""),[answer,setAnswer]=useState("Ask what needs your attention today.");
useEffect(()=>{const s=localStorage.getItem("buildguard-projects");setProjects(s?JSON.parse(s):starter);setLoaded(true)},[]);
useEffect(()=>{if(loaded)localStorage.setItem("buildguard-projects",JSON.stringify(projects))},[projects,loaded]);
const total=useMemo(()=>projects.reduce((s,p)=>s+p.valueCr,0),[projects]),issues=useMemo(()=>projects.filter(p=>health(p).label!=="Healthy").length,[projects]);
function resetDemo(){setProjects(starter);setSelected(null);localStorage.removeItem("buildguard-documents")}
function ask(){const p=selected||projects[0];if(!p)return;const x=q.toLowerCase(),gap=p.planned-p.progress,b=p.budgetActual-p.budgetPlan;if(x.includes("budget")||x.includes("cost"))setAnswer(b>0?`${p.name} is ₹${b.toFixed(1)}L above the current control budget.`:`${p.name} is currently within the control budget.`);else if(x.includes("delay")||x.includes("risk")||x.includes("late"))setAnswer(gap>0?`${p.name} is ${gap}% behind planned progress and should be reviewed for blocked activities and pending procurement.`:`${p.name} is currently on or ahead of plan.`);else setAnswer(`${p.name}: actual progress ${p.progress}% vs ${p.planned}% planned. ${b>0?`Budget variance is +₹${b.toFixed(1)}L.`:"No current budget overrun detected."}`);setQ("")}
if(!loaded)return <div className="loading">BuildGuard AI</div>;
return <div className="shell"><aside className="sidebar"><div className="brand"><div>BG</div><span>BuildGuard AI</span></div><nav><b>Overview</b><span>Projects</span><span>Procurement</span><span>Budget</span><span>Risk center</span><span>Documents</span><span>AI analyst</span></nav><div className="sidebarBottom"><small>Public demo mode</small><button onClick={resetDemo}><RotateCcw size={15}/> Reset demo</button></div></aside>
<main className="main"><header className="top"><div><span className="eyebrow">EXECUTIVE CONTROL ROOM</span><h1>Portfolio overview</h1><p>See where projects may lose time or money before the problem becomes expensive.</p></div><div className="actions"><button className="secondary" onClick={()=>setShowUpload(true)}><UploadCloud size={16}/> Upload document</button><button className="primary" onClick={()=>setShowNew(true)}><Plus size={16}/> New project</button></div></header>
<div className="demoBanner"><Sparkles size={16}/><div><b>Client demo mode</b><span>No login required. Changes are saved only in this browser.</span></div></div>
<section className="metrics"><div><span>Active projects</span><strong>{projects.length}</strong><small>Current browser workspace</small></div><div><span>Total project value</span><strong>₹{total} Cr</strong><small>Portfolio value</small></div><div><span>Projects needing attention</span><strong>{issues}</strong><small>Schedule or budget exceptions</small></div><div><span>Demo workspace</span><strong>Live</strong><small>No account required</small></div></section>
<section className="grid"><div><div className="panel heroRisk"><span className="riskBadge"><TriangleAlert size={14}/> Critical procurement risk</span><h2>40 MT steel shortfall may delay Tower B structural work</h2><p>110 MT is required. Inventory covers 32 MT and purchase orders cover 38 MT. The remaining 40 MT is still uncovered.</p><div className="riskStats"><div><span>Required by</span><b>24 Sep</b></div><div><span>Lead time</span><b>6–16 days</b></div><div><span>Potential impact</span><b>High</b></div></div></div>
<div className="panel"><div className="panelHead"><div><h2>Projects</h2><p>Actual progress against current plan</p></div></div><div className="table"><div className="tr th"><span>Project</span><span>Progress</span><span>Schedule</span><span>Value</span><span>Health</span></div>{projects.map(p=>{const h=health(p),gap=p.planned-p.progress;return <button className="tr projectRow" key={p.id} onClick={()=>setSelected(p)}><span><b>{p.name}</b><small>{p.city}</small></span><span><div className="barLabel"><small>{p.progress}%</small><small>Plan {p.planned}%</small></div><div className="bar"><i style={{width:`${Math.min(100,p.progress)}%`}}/></div></span><span className={gap>0?"danger":"good"}>{gap>0?`${gap}% behind`:"On track"}</span><span>₹{p.valueCr} Cr</span><span><em className={`pill ${h.tone}`}>{h.label}</em></span></button>})}</div></div>
<div className="panel"><div className="panelHead"><div><h2>Steel vendor decision</h2><p>Price + delivery + payment terms</p></div><span className="pill green">Recommended</span></div><div className="vendors"><div className="vrow vh"><span>Vendor</span><span>Rate</span><span>Delivery</span><span>Payment</span><span>AI score</span></div><div className="vrow recommended"><span><b>BuildRight Metals</b><small>Recommended</small></span><span>₹59,800/MT</span><span>9 days</span><span>30 days credit</span><span><b>94/100</b></span></div><div className="vrow"><span><b>Shree Steel</b></span><span>₹61,500/MT</span><span>6 days</span><span>30 days credit</span><span><b>86/100</b></span></div><div className="vrow"><span><b>Metro Metals</b></span><span>₹57,900/MT</span><span>16 days</span><span>50% advance</span><span><b>68/100</b></span></div></div></div></div>
<aside><div className="aiCard"><div className="aiTitle"><Sparkles size={18}/><h3>AI Project Analyst</h3></div><p>{answer}</p><div className="chips"><button onClick={()=>setQ("What is the biggest delay risk?")}>Delay risk?</button><button onClick={()=>setQ("Where are we over budget?")}>Budget issue?</button></div><div className="ask"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&ask()} placeholder="Ask about a project..."/><button onClick={ask}>↗</button></div></div><div className="panel"><h3>Selected project</h3>{selected?<div className="selected"><div className="selectedIcon"><Building2/></div><h2>{selected.name}</h2><p>{selected.city} · {selected.type}</p><div className="selectedStats"><div><span>Actual</span><b>{selected.progress}%</b></div><div><span>Planned</span><b>{selected.planned}%</b></div><div><span>Value</span><b>₹{selected.valueCr} Cr</b></div></div></div>:<p className="muted">Select a project from the table.</p>}</div><div className="panel"><h3>Today's priorities</h3><div className="priorities"><div><i>1</i><span><b>Steel purchase decision</b><small>40 MT remains uncovered.</small></span></div><div><i>2</i><span><b>Electrical RFQ pending</b><small>Three quotations are ready.</small></span></div><div><i>3</i><span><b>Budget variance</b><small>Electrical package is above plan.</small></span></div></div></div></aside></section></main>
{showNew&&<NewProjectModal onClose={()=>setShowNew(false)} onCreate={p=>{setProjects([p,...projects]);setShowNew(false)}}/>}{showUpload&&<UploadModal onClose={()=>setShowUpload(false)}/>}</div>}
function NewProjectModal({onClose,onCreate}:{onClose:()=>void;onCreate:(p:Project)=>void}){const[f,setF]=useState({name:"",city:"",type:"Residential",valueCr:"",progress:"0",planned:"0",budgetPlan:"0",budgetActual:"0"});function create(){onCreate({id:Date.now().toString(),name:f.name,city:f.city,type:f.type,valueCr:Number(f.valueCr||0),progress:Number(f.progress||0),planned:Number(f.planned||0),budgetPlan:Number(f.budgetPlan||0),budgetActual:Number(f.budgetActual||0)})}return <div className="modalBg"><div className="modal"><div className="modalTop"><div><span className="eyebrow">DEMO WORKSPACE</span><h2>Create project</h2></div><button onClick={onClose}>×</button></div><div className="formGrid"><label className="full">Project name<input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>City<input value={f.city} onChange={e=>setF({...f,city:e.target.value})}/></label><label>Type<select value={f.type} onChange={e=>setF({...f,type:e.target.value})}><option>Residential</option><option>Commercial</option><option>Mixed-use</option><option>Villas</option></select></label><label>Project value (₹ Cr)<input type="number" value={f.valueCr} onChange={e=>setF({...f,valueCr:e.target.value})}/></label><label>Actual progress %<input type="number" value={f.progress} onChange={e=>setF({...f,progress:e.target.value})}/></label><label>Planned progress %<input type="number" value={f.planned} onChange={e=>setF({...f,planned:e.target.value})}/></label><label>Budget planned (₹ L)<input type="number" value={f.budgetPlan} onChange={e=>setF({...f,budgetPlan:e.target.value})}/></label><label>Budget actual (₹ L)<input type="number" value={f.budgetActual} onChange={e=>setF({...f,budgetActual:e.target.value})}/></label></div><button className="saveBtn" onClick={create} disabled={!f.name}>Create project</button></div></div>}
function UploadModal({onClose}:{onClose:()=>void}){const[file,setFile]=useState<File|null>(null),[category,setCategory]=useState("BOQ"),[saved,setSaved]=useState(false);function save(){if(!file)return;const docs=JSON.parse(localStorage.getItem("buildguard-documents")||"[]");docs.unshift({name:file.name,category,size:file.size,createdAt:new Date().toISOString()});localStorage.setItem("buildguard-documents",JSON.stringify(docs));setSaved(true)}return <div className="modalBg"><div className="modal"><div className="modalTop"><div><span className="eyebrow">DEMO DOCUMENTS</span><h2>Upload document</h2></div><button onClick={onClose}>×</button></div><label>Document type<select value={category} onChange={e=>setCategory(e.target.value)}><option>BOQ</option><option>Schedule</option><option>Budget</option><option>Vendor Quote</option><option>Purchase Order</option><option>Invoice</option><option>Progress Report</option></select></label><label className="fileDrop"><UploadCloud/><b>{file?file.name:"Choose a project file"}</b><span>This public demo stores only file metadata in your browser.</span><input type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>{saved&&<div className="success"><CheckCircle2 size={16}/> Demo upload saved in this browser.</div>}<button className="saveBtn" onClick={save} disabled={!file}>Save demo upload</button></div></div>}
